# Generated by Django 4.0.1 on 2022-02-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='readStatus',
            field=models.BooleanField(default=False),
        ),
    ]
